### Değişken Standardizasyonu

In [2]:
import numpy as np
import pandas as pd
V1 = np.array([1,3,6,5,7])
V2 = np.array([7,7,5,8,12])
V3 = np.array([6,12,5,6,14])
df = pd.DataFrame(
            {"V1" : V1,
             "V2" : V2,
             "V3" : V3
            }
)
df = df.astype(float)
df

V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

#### Standardizasyon

In [4]:
from sklearn import preprocessing

In [6]:
preprocessing.scale(df) #yapışarı birbiriyle kıyaslanabilirliği bozulmadı
#değişkenleri standartlaştırıp algoritmayı yormayız

array([[-1.57841037, -0.34554737, -0.70920814],
       [-0.64993368, -0.34554737,  0.92742603],
       [ 0.74278135, -1.2094158 , -0.98198051],
       [ 0.27854301,  0.08638684, -0.70920814],
       [ 1.2070197 ,  1.81412369,  1.47297076]])

#### Normalizasyon
Değişkenleri 0-1 arasına almak için kullanılır.

In [8]:
preprocessing.normalize(df)

array([[0.10783277, 0.75482941, 0.64699664],
       [0.21107926, 0.49251828, 0.84431705],
       [0.64699664, 0.53916387, 0.53916387],
       [0.4472136 , 0.71554175, 0.53665631],
       [0.35491409, 0.60842415, 0.70982818]])

#### Min-Max Dönüşümleri
Kendi istediğimiz aralıklara çekeriz değişkenleri

In [9]:
scaler =preprocessing.MinMaxScaler(feature_range=(10,20))

In [10]:
scaler.fit_transform(df)

array([[10.        , 12.85714286, 11.11111111],
       [13.33333333, 12.85714286, 17.77777778],
       [18.33333333, 10.        , 10.        ],
       [16.66666667, 14.28571429, 11.11111111],
       [20.        , 20.        , 20.        ]])

### Değişken Dönüşümleri
Her standartliazasyon bir değişken dönüşümüdür. Önemli olan değişkenin yapısın bozulup bozulmamasıdır

In [12]:
import seaborn as sns
df = sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

##### 0-1 Dönüşümü

In [14]:
from sklearn.preprocessing import LabelEncoder

lbe = LabelEncoder()

In [17]:
df["yeni_sex"] = lbe.fit_transform(df['sex']) #cinsiyet değişkenini 1 ve 0 a dönüştürdük

In [20]:
df #veriye göre neye 1 neye 0 verdiğine dikkat edelim

total_bill   tip     sex smoker   day    time  size  yeni_sex
0         16.99  1.01  Female     No   Sun  Dinner     2         0
1         10.34  1.66    Male     No   Sun  Dinner     3         1
2         21.01  3.50    Male     No   Sun  Dinner     3         1
3         23.68  3.31    Male     No   Sun  Dinner     2         1
4         24.59  3.61  Female     No   Sun  Dinner     4         0
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         1
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         1
242       17.82  1.75    Male     No   Sat  Dinner     2         1
243       18.78  3.00  Female     No  Thur  Dinner     2         0

[244 rows x 8 columns]

##### "1 ve Diğerleri (0) Dönüşümü

In [21]:
df.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         0
1       10.34  1.66    Male     No  Sun  Dinner     3         1
2       21.01  3.50    Male     No  Sun  Dinner     3         1
3       23.68  3.31    Male     No  Sun  Dinner     2         1
4       24.59  3.61  Female     No  Sun  Dinner     4         0

In [25]:
df["yeni_day"] = np.where(df["day"].str.contains("Sun"),1,0)
#içinde sun olan str şeklindeki değerler yerine 1 diğerlerine de 0 yaz dedik

In [26]:
df

total_bill   tip     sex smoker   day    time  size  yeni_sex  yeni_day
0         16.99  1.01  Female     No   Sun  Dinner     2         0         1
1         10.34  1.66    Male     No   Sun  Dinner     3         1         1
2         21.01  3.50    Male     No   Sun  Dinner     3         1         1
3         23.68  3.31    Male     No   Sun  Dinner     2         1         1
4         24.59  3.61  Female     No   Sun  Dinner     4         0         1
..          ...   ...     ...    ...   ...     ...   ...       ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         1         0
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0         0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         1         0
242       17.82  1.75    Male     No   Sat  Dinner     2         1         0
243       18.78  3.00  Female     No  Thur  Dinner     2         0         0

[244 rows x 9 columns]

#### Çok Sınıflı Dönüşüm

In [27]:
from sklearn.preprocessing import LabelEncoder
lbe = LabelEncoder()

In [28]:
lbe.fit_transform(df["day"]) #day içindeki sınıflar numerik değerlere dönüştü
#fakat günleri sayıya çevirdiğimiz için günler değei olmuş olur

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

#### One-Hot Dönüşümü ve Dummy Değişken Tuzağı

In [29]:
df.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex  yeni_day
0       16.99  1.01  Female     No  Sun  Dinner     2         0         1
1       10.34  1.66    Male     No  Sun  Dinner     3         1         1
2       21.01  3.50    Male     No  Sun  Dinner     3         1         1
3       23.68  3.31    Male     No  Sun  Dinner     2         1         1
4       24.59  3.61  Female     No  Sun  Dinner     4         0         1

In [32]:
df_one_hot = pd.get_dummies(df,columns = ["sex"],prefix =["sex"])

In [34]:
df_one_hot.head()
#cinsiyetleri kategorik olarak ayırıp 1 ve 0 a dönüştürüyoruz bune one hot denir

total_bill   tip smoker  day    time  size  yeni_sex  yeni_day  sex_Male  \
0       16.99  1.01     No  Sun  Dinner     2         0         1         0   
1       10.34  1.66     No  Sun  Dinner     3         1         1         1   
2       21.01  3.50     No  Sun  Dinner     3         1         1         1   
3       23.68  3.31     No  Sun  Dinner     2         1         1         1   
4       24.59  3.61     No  Sun  Dinner     4         0         1         0   

   sex_Female  
0           1  
1           0  
2           0  
3           0  
4           1

In [35]:
#oluşan iki değişkende aynı bilgiyi taşır bi tanesi ile cinsiyeti anlayabiliyoruz
#bu duruma dummy değişken tuzağı denir
#bunu kategorik değişken sınıfın dan 1 az değişken olmalı ki bu tuzağa düşmeyelin

In [36]:
pd.get_dummies(df,columns = ["day"],prefix =["day"]).head()

total_bill   tip     sex smoker    time  size  yeni_sex  yeni_day  \
0       16.99  1.01  Female     No  Dinner     2         0         1   
1       10.34  1.66    Male     No  Dinner     3         1         1   
2       21.01  3.50    Male     No  Dinner     3         1         1   
3       23.68  3.31    Male     No  Dinner     2         1         1   
4       24.59  3.61  Female     No  Dinner     4         0         1   

   day_Thur  day_Fri  day_Sat  day_Sun  
0         0        0        0        1  
1         0        0        0        1  
2         0        0        0        1  
3         0        0        0        1  
4         0        0        0        1